language: java
notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
matrix:
  include:
  - os: osx
  - os: linux
    jdk: oraclejdk10
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: openjdk12
  - os: linux
    jdk: oraclejdk10
    arch: ppc64le
  - os: linux
    jdk: openjdk11
    arch: ppc64le
  - os: linux
    jdk: openjdk12
    arch: ppc64le

sudo: false
cache:
  directories:
  - $HOME/.m2
script:
  - mvn test -B
  - mvn test -B -Djnr.constants.fake=false
